app_config:
  community_program:
    completion_policy:
      weights:
        -
          value: 0.30
          fields:
            - :name
            - :service_description
            - :quality_element
            - :service_types
            - :organization
        -
          value: 0.35
          fields:
            - :days
            - :demographic_groups
            - :ethnicity_culture_groups
            - :grade_levels
            - :service_times
            - :student_population
            - :user
        -
          value: 0.35
          fields:
            - :school_programs

    public_policy:
      percentage_complete: 0.30
      required_attributes: []
      public_attributes:
        - :name
        - :service_description
        - :quality_element
        - :service_types
        - :grade_level_ids
      verification_required: true

    validations:
      -
        attribute: :name
        options:
          presence:
            message: must choose a program name
      -
        attribute: :organization_id
        options:
          presence:
            message: must choose an organization
      -
        attribute: :user_id
        options:
          presence:
            message: must choose an organization contact
      -
        attribute: :primary_quality_element
        options:
          presence:
            message: must choose a primary quality element

    verification_policy:
      verification_date: '2017-06-01'
      grace_period_end_date: '2017-08-01'
