app_config:
  organization:
    completion_policy:
      weights:
        -
          value: 0.25
          fields:
            - :required_fields
        -
          value: 0.75
          fields:
            - :address
            - :city
            - :cost_per_student
            - :mission_statement
            - :mou_on_file
            - :phone_number
            - :program_impact
            - :services_description
            - :url
            - :zip_code

    validations:
      -
        attribute: :name
        options:
          presence: true
      -
        attribute: :legal_status_id
        options:
          presence:
            message: Please choose from the list above
