app_config:
  organization:

    validations:
      -
        attribute: :name
        options:
          presence: true
      -
        attribute: :legal_status_id
        options:
          presence:
            message: Please choose from the list above
