app_config:
  organization:
    completion_policy:
      weights:
        -
          value: 0.25
          fields:
            - :required_fields
        -
          value: 0.75
          fields:
            - :address
            - :city
            - :total_cost
            - :mission_statement
            - :board_approved_contract
            - :phone_number
            - :program_impact
            - :services_description
            - :url
            - :zip_code

    public_policy:
      percentage_complete: 0.75
      required_attributes: []
      public_attributes:
        - :name
        - :total_cost
        - :url
        - :user_id
      verification_required: true

    validations:
      -
        attribute: :name
        options:
          presence: true
      -
        attribute: :legal_status_id
        options:
          presence:
            message: Please choose from the list above

    verification_policy:
      verification_date: '2017-06-01'
      grace_period_end_date: '2017-08-01'
