app_config:
  community_program:
    completion_policy:
      weights:
        -
          value: 0.30
          fields:
            - :name
            - :organization
            - :quality_element
            - :service_description
            - :service_types
        -
          value: 0.35
          fields:
            - :days
            - :demographic_groups
            - :ethnicity_culture_groups
            - :grade_levels
            - :service_times
            - :student_population
            - :user
        -
          value: 0.35
          fields:
            - :school_programs

    fields:
      fields_to_skip:
        - :personal_services_contract
        - :memorandum_of_understanding
        - :alignment_agreement
        - :data_sharing_agreement
        - :levy_funded

    public_policy:
      percentage_complete: 0.75
      required_attributes: []
      public_attributes:
        - :grade_level_ids
        - :name
        - :quality_element
        - :service_description
        - :service_types
      verification_required: true

    validations:
      -
        attribute: :name
        options:
          presence:
            message: must choose a program name
      -
        attribute: :organization_id
        options:
          presence:
            message: must choose an organization
      -
        attribute: :user_id
        options:
          presence:
            message: must choose an organization contact
      -
        attribute: :primary_quality_element
        options:
          presence:
            message: must choose a primary quality element

    verification_policy:
      verification_date: '2019-08-08'
      grace_period_end_date: '2019-10-31'
