version: 2.1

orbs:
  cj: criticaljuncture/cj-orb@0.1

workflows:
  workflow:
    jobs:
      - cj/build_rails_image:
          branch: << pipeline.git.branch >>
          context: [orb-slack, pilot, cj-ecr] # add additional CircleCI contexts here if desired
          repo_image: community-partner-platform
          ecr: true
          skip_lint: true # disable lint
          test_command: docker-compose -f docker/compose/ci.yml run web bash -c "bin/wait_for_mysql && rake parallel:setup && RAILS_ENV=test rake parallel:migrate && parallel_rspec -o '--tag ~no_ci'"
