#= require jquery
#= require jquery_ujs

#= require bootstrap/alert
#= require bootstrap/dropdown
#= require bootstrap/modal
#= require bootstrap/tab
#= require bootstrap-datepicker/core
#= require bootstrap-datepicker-rails
#= require colorbrewer
#= require d3
# require handlebars
#= require handlebars.runtime
#= require js-routes
#= require jquery.cookie
#= require jquery.parsequery.js
#= require jquery.tablesorter.min
#= require jquery.tablesorter.widgets.min
#= require jquery.tipsy.svg.js
#= require underscore
