web:
  extends:
    file: shared.yml
    service: web
  environment:
    - RAILS_ENV=test
    - MYSQL_DATABASE=community_partner_platform
  links:
    - mariadb
    - redis

mariadb:
  extends:
    file: shared.yml
    service: mariadb

redis:
  extends:
    file: shared.yml
    service: redis
