services:
  web:
    extends:
      file: shared.yml
      service: web
    environment:
      - RAILS_ENV=test
    image: $CI_IMAGE
    volumes:
      - /tmp/test-results:/home/app/tmp/test-results
    links:
      - mariadb
      - redis

  mariadb:
    extends:
      file: shared.yml
      service: mariadb

  redis:
    extends:
      file: shared.yml
      service: redis
